export const elementsLocators = {
  permanentAddressInput: '#permanentAddress',
  btnsFechadosSelector: 'button[aria-label="Toggle"] svg.rct-icon-expand-close',
  checkboxName: '#result',
  addTable: '#addNewRecordButton',
  firstEditButton: '#edit-record-1',
  firstDeleteButton: '#delete-record-1',
  homeLink: '#simpleLink',
  homeURMqOLink: '#dynamicLink',
  linkResponse: '#linkResponse',
  createdLink: '#created',
  noContentLink: '#no-content',
  movedLink: '#moved',
  badRequestLink: '#bad-request',
  unauthorizedLink: '#unauthorized',
  forbiddenLink: '#forbidden',
  notFoundLink: '#invalid-url',
  uploadedFilePath: '#uploadedFilePath',
  enableDynamicButton: '#enableAfter',
  colorDynamicButton: '#colorChange',
  visibleDynamicButton: '#visibleAfter',
}