export const widgetLocators = {
  autoCompleteMultipleInput: '#autoCompleteMultipleInput',
  selectOptionMultiple: '#react-select-2-option-0',
  autoCompleteSingleInput: '#autoCompleteSingleInput',
  selectOptionSingle: '#react-select-3-option-0',
  autoCompleteSingleContainer: '#autoCompleteSingleContainer div',
  datePickerMonthYearInput: '#datePickerMonthYearInput',
  dateAndTimePickerInput: '#dateAndTimePickerInput',
  dateAndTimePicker: '#dateAndTimePicker span',
  sliderValue: '#sliderValue',
  progressBar: '#progressBar',
  selectValueMenu: '#withOptGroup svg',
  selectValueOption: '#selectMenuContainer div',
  selectOneMenu: '#selectOne svg',
  oldStyleSelectMenu: '#oldSelectMenu',
  multiselectDropDown: '#selectMenuContainer svg',
  colorOptions: {
    Green: '#react-select-4-option-0',
    Blue: '#react-select-4-option-1',
    Black: '#react-select-4-option-2',
    Red: '#react-select-4-option-3',
  },
}